name: Deploy to AWS Elastic Beanstalk
   
on:
  push:
    branches: [main] 
  
jobs:  
  deploy:  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 20

      - name: Install dependencies
        run: |
          cd pixalivetech_backend
          npm install --legacy-peer-deps

      - name: Build TypeScript
        run: |
          cd pixalivetech_backend
          npm run build

      - name: Create deployment package
        run: |
          cd pixalivetech_backend
          zip -r server.zip . -x "*.git*" "node_modules/*" ".github/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: demo                      # Change to your real app name
          environment_name: Demo-env                 # Change to your real environment name
          region: ${{ secrets.AWS_REGION }}
          version_label: "v-${{ github.sha }}"
          deployment_package: pixalivetech_backend/server.zip
          existing_bucket_name: pix-tech
          use_existing_version_if_available: true
