name: Deploy to AWS Elastic Beanstalk
   
on:
  push:
    branches: [main] 
 
jobs:  
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build TypeScript
        run: npm run build

      - name: Create deployment package
        run: zip -r server.zip . -x "*.git*" "node_modules/*" ".github/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: demo                      # Change if your app is not "demo"
          environment_name: Demo-env                 # Change if your env is not "Demo-env"
          region: ${{ secrets.AWS_REGION }}
          version_label: "v-${{ github.sha }}"
          deployment_package: server.zip
          existing_bucket_name: pix-tech
          use_existing_version_if_available: true
